spring.application.name=cbar
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
jwt.secret=Y2JhckFwcFN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb24yMDI1
jwt.expiration-ms=86400000
cbar.base-url=https://www.cbar.az/currencies
